/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.brechosustentavel.view;

import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author thiag
 */
public class AnuncioView extends javax.swing.JInternalFrame implements IAnuncioView{

    /**
     * Creates new form ManterItemView
     */
    public AnuncioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        labelId_c = new javax.swing.JLabel();
        labelTipoPeca = new javax.swing.JLabel();
        txtId_c = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        txtMassa = new javax.swing.JTextField();
        txtEstadoConservacao = new javax.swing.JTextField();
        txtPrecoBase = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        labelSubcategoria = new javax.swing.JLabel();
        labelEstadoConservacao = new javax.swing.JLabel();
        labelPrecoBase = new javax.swing.JLabel();
        labelCor = new javax.swing.JLabel();
        labelMassa = new javax.swing.JLabel();
        labelComposicao = new javax.swing.JLabel();
        labelDefeitos = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        selectComposicao = new javax.swing.JComboBox<>();
        selectDefeitos = new javax.swing.JComboBox<>();
        selectSubcategoria = new javax.swing.JComboBox<>();
        btnEnviar1 = new javax.swing.JButton();
        selectTipoDePeca = new javax.swing.JComboBox<>();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(1000, 700));

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelId_c.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelId_c.setText("ID_C");
        labelId_c.setToolTipText("");

        labelTipoPeca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTipoPeca.setText("Tipo de Peça");

        txtId_c.setToolTipText("Digite o ID_C (Caso não possua deixe em branco)");
        txtId_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_cActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelTitulo.setText("Novo anúncio");

        txtTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanhoActionPerformed(evt);
            }
        });

        txtMassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMassaActionPerformed(evt);
            }
        });

        txtEstadoConservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoConservacaoActionPerformed(evt);
            }
        });

        txtPrecoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoBaseActionPerformed(evt);
            }
        });

        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        labelSubcategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubcategoria.setText("Subcategoria");

        labelEstadoConservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEstadoConservacao.setText("Estado de conservação");
        labelEstadoConservacao.setToolTipText("");

        labelPrecoBase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPrecoBase.setText("Preço-base (R$)");

        labelCor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCor.setText("Cor Predominante");

        labelMassa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMassa.setText("Massa Estimada (g)");

        labelComposicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelComposicao.setText("Composição Principal");

        labelDefeitos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDefeitos.setText("Defeitos");

        labelTamanho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTamanho.setText("Tamanho");

        selectComposicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectDefeitos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectSubcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEnviar1.setText("Cancelar");

        selectTipoDePeca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectTipoDePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoDePecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelId_c, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId_c, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(txtCor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMassa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSubcategoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMassa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDefeitos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectDefeitos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectSubcategoria, 0, 373, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(246, 504, Short.MAX_VALUE)
                        .addComponent(btnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoPeca)
                    .addComponent(labelTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelComposicao)
                    .addComponent(labelEstadoConservacao)
                    .addComponent(labelPrecoBase)
                    .addComponent(selectComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTipoDePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo)
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTipoDePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMassa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstadoConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstadoConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMassa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        txtId_c.getAccessibleContext().setAccessibleName("Digite o ID_C (Caso não possua deixe em branco)");

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);
        panel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtPrecoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoBaseActionPerformed

    private void txtEstadoConservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoConservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoConservacaoActionPerformed

    private void txtMassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMassaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMassaActionPerformed

    private void txtTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanhoActionPerformed

    private void txtId_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_cActionPerformed

    private void selectTipoDePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoDePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoDePecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JLabel labelComposicao;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelDefeitos;
    private javax.swing.JLabel labelEstadoConservacao;
    private javax.swing.JLabel labelId_c;
    private javax.swing.JLabel labelMassa;
    private javax.swing.JLabel labelPrecoBase;
    private javax.swing.JLabel labelSubcategoria;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelTipoPeca;
    private javax.swing.JLabel labelTitulo;
    private java.awt.Panel panel1;
    private javax.swing.JComboBox<String> selectComposicao;
    private javax.swing.JComboBox<String> selectDefeitos;
    private javax.swing.JComboBox<String> selectSubcategoria;
    private javax.swing.JComboBox<String> selectTipoDePeca;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtEstadoConservacao;
    private javax.swing.JTextField txtId_c;
    private javax.swing.JTextField txtMassa;
    private javax.swing.JTextField txtPrecoBase;
    private javax.swing.JTextField txtTamanho;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComboBox<String> getSelectComposicao() {
        return selectComposicao;
    }
    
    @Override
    public JComboBox<String> getSelectDefeitos() {
        return selectDefeitos;
    }
    
    @Override
    public JComboBox<String> getSelectSubcategoria() {
        return selectSubcategoria;
    }
    
    @Override
    public JTextField getTxtCor() {
        return txtCor;
    }
    
    @Override
    public JTextField getTxtEstadoConservacao() {
        return txtEstadoConservacao;
    }

    @Override
    public JTextField getTxtId_c() {
        return txtId_c;
    }

    @Override
    public JTextField getTxtMassa() {
        return txtMassa;
    }

    @Override
    public JTextField getTxtTamanho() {
        return txtTamanho;
    }

    @Override
    public JComboBox<String> getSelectTipoDePeca() {
        return selectTipoDePeca;
    }

    @Override
    public JTextField getTxtPrecoBase() {
        return txtPrecoBase;
    }
    

}


