/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.brechosustentavel.view;

import javax.swing.JPanel;

/**
 *
 * @author thiag
 */
public class JanelaDashboardView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardView
     */
    public JanelaDashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReputacao = new javax.swing.JPanel();
        panelGwp = new javax.swing.JPanel();
        panelMateriais = new javax.swing.JPanel();
        panelRanking = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dashboard");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        panelReputacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Distribuição de Níveis de Reputação"));

        javax.swing.GroupLayout panelReputacaoLayout = new javax.swing.GroupLayout(panelReputacao);
        panelReputacao.setLayout(panelReputacaoLayout);
        panelReputacaoLayout.setHorizontalGroup(
            panelReputacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panelReputacaoLayout.setVerticalGroup(
            panelReputacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(panelReputacao);

        panelGwp.setBorder(javax.swing.BorderFactory.createTitledBorder("Evolução Semanal de GWP Evitado"));

        javax.swing.GroupLayout panelGwpLayout = new javax.swing.GroupLayout(panelGwp);
        panelGwp.setLayout(panelGwpLayout);
        panelGwpLayout.setHorizontalGroup(
            panelGwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panelGwpLayout.setVerticalGroup(
            panelGwpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(panelGwp);

        panelMateriais.setBorder(javax.swing.BorderFactory.createTitledBorder("Participação de Materiais na Massa Circulante"));

        javax.swing.GroupLayout panelMateriaisLayout = new javax.swing.GroupLayout(panelMateriais);
        panelMateriais.setLayout(panelMateriaisLayout);
        panelMateriaisLayout.setHorizontalGroup(
            panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panelMateriaisLayout.setVerticalGroup(
            panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(panelMateriais);

        panelRanking.setBorder(javax.swing.BorderFactory.createTitledBorder("Ranking de Crescimento Vigente"));

        javax.swing.GroupLayout panelRankingLayout = new javax.swing.GroupLayout(panelRanking);
        panelRanking.setLayout(panelRankingLayout);
        panelRankingLayout.setHorizontalGroup(
            panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panelRankingLayout.setVerticalGroup(
            panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(panelRanking);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelGwp;
    private javax.swing.JPanel panelMateriais;
    private javax.swing.JPanel panelRanking;
    private javax.swing.JPanel panelReputacao;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanelGwp() {
        return panelGwp;
    }

    public JPanel getPanelMateriais() {
        return panelMateriais;
    }

    public JPanel getPanelRanking() {
        return panelRanking;
    }

    public JPanel getPanelReputacao() {
        return panelReputacao;
    }
    

}
