/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.brechosustentavel.view;

import java.beans.PropertyVetoException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author thiag
 */
public class JanelaPrincipalView extends javax.swing.JInternalFrame implements IJanelaPrincipalView{

    /**
     * Creates new form JanelaPrincipal
     * @throws java.beans.PropertyVetoException
     */
    public JanelaPrincipalView() throws PropertyVetoException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        cBoxCriterioFiltro = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        lblSubtitulo = new javax.swing.JLabel();
        cBoxValorFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonVisualizar = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        buttonManterTipo = new javax.swing.JButton();
        buttonManterComposicao = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuVisualizarPerfil = new javax.swing.JMenu();
        menuPerfil = new javax.swing.JMenu();
        opcTrocarPerfil = new javax.swing.JMenuItem();
        opcAddPerfil = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        opcExportarLogs = new javax.swing.JMenuItem();
        opcExportarVendas = new javax.swing.JMenuItem();
        menuConfiguracao = new javax.swing.JMenu();
        menuTransacao = new javax.swing.JMenu();
        opcAvaliar = new javax.swing.JMenuItem();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bem-vindo Vendedor!");
        setPreferredSize(new java.awt.Dimension(1000, 677));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFiltrar.setText("Filtrar");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("FILTRAR POR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSubtitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cBoxCriterioFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBoxValorFiltro, 0, 224, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxCriterioFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonVisualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonVisualizar.setText("Visualizar");
        buttonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarActionPerformed(evt);
            }
        });

        buttonAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAdicionar.setText("Adicionar Anúncio");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonManterTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonManterTipo.setText("Gerenciar tipos de peças");
        buttonManterTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManterTipoActionPerformed(evt);
            }
        });

        buttonManterComposicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonManterComposicao.setText("Gerenciar Composicoes");
        buttonManterComposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManterComposicaoActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ANÚNCIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(buttonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(buttonManterTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(buttonManterComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonManterTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonManterComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        menuVisualizarPerfil.setText("Visualizar Perfil");
        menuBar.add(menuVisualizarPerfil);

        menuPerfil.setText("Perfil");
        menuPerfil.setToolTipText("");

        opcTrocarPerfil.setText("Trocar perfil");
        menuPerfil.add(opcTrocarPerfil);

        opcAddPerfil.setText("Adicionar novo perfil");
        menuPerfil.add(opcAddPerfil);

        menuBar.add(menuPerfil);

        menuRelatorios.setText("Relatórios");

        opcExportarLogs.setText("Exportar Logs");
        menuRelatorios.add(opcExportarLogs);

        opcExportarVendas.setText("Exportar Vendas");
        menuRelatorios.add(opcExportarVendas);

        menuBar.add(menuRelatorios);

        menuConfiguracao.setText("Configuração");
        menuBar.add(menuConfiguracao);

        menuTransacao.setText("Minhas Compras");

        opcAvaliar.setText("Avaliar compras");
        menuTransacao.add(opcAvaliar);

        menuBar.add(menuTransacao);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVisualizarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonManterTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManterTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonManterTipoActionPerformed

    private void buttonManterComposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManterComposicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonManterComposicaoActionPerformed

    @Override
    public JButton getButtonAdicionar() {
        return buttonAdicionar;
    }

    @Override
    public JButton getButtonVisualizar() {
        return buttonVisualizar;
    }

    @Override
    public JTable getjTable1() {
        return jTable1;
    }

    public JMenu getMenuConfiguracao() {
        return menuConfiguracao;
    }

    public JMenu getMenuPerfil() {
        return menuPerfil;
    }

    public JMenu getMenuVisualizarPerfil() {
        return menuVisualizarPerfil;
    }

    public JMenuItem getOpcAddPerfil() {
        return opcAddPerfil;
    }

    public JMenuItem getOpcTrocarPerfil() {
        return opcTrocarPerfil;
    }

    public JButton getButtonManterTipo() {
        return buttonManterTipo;
    }

    public JButton getButtonManterComposicao() {
        return buttonManterComposicao;
    }

    public JMenuItem getOpcExportarVendas() {
        return opcExportarVendas;
    }

    public JMenu getMenuRelatorios() {
        return menuRelatorios;
    }

    public JMenuItem getOpcExportarLogs() {
        return opcExportarLogs;
    }

    public JButton getBtnFiltrar() {
        return btnFiltrar;
    }

    public JComboBox<String> getcBoxCriterioFiltro() {
        return cBoxCriterioFiltro;
    }

    public JComboBox<String> getcBoxValorFiltro() {
        return cBoxValorFiltro;
    }

    public JTextField getTxtAtributos() {
        return txtAtributos;
    }

    public JMenuItem getOpcAvaliar() {
        return opcAvaliar;
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonManterComposicao;
    private javax.swing.JButton buttonManterTipo;
    private javax.swing.JButton buttonVisualizar;
    private javax.swing.JComboBox<String> cBoxCriterioFiltro;
    private javax.swing.JComboBox<String> cBoxValorFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConfiguracao;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuTransacao;
    private javax.swing.JMenu menuVisualizarPerfil;
    private javax.swing.JMenuItem opcAddPerfil;
    private javax.swing.JMenuItem opcAvaliar;
    private javax.swing.JMenuItem opcExportarLogs;
    private javax.swing.JMenuItem opcExportarVendas;
    private javax.swing.JMenuItem opcTrocarPerfil;
    private javax.swing.JTextField txtAtributos;
    // End of variables declaration//GEN-END:variables
}
