/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.brechosustentavel.view;

import java.beans.PropertyVetoException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author thiag
 */
public class JanelaManterAnuncioView extends javax.swing.JInternalFrame implements IJanelaManterAnuncioView{

    /**
     * Creates new form ManterItemView
     * @throws java.beans.PropertyVetoException
     */
    public JanelaManterAnuncioView() throws PropertyVetoException{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        labelId_c = new javax.swing.JLabel();
        labelTipoPeca = new javax.swing.JLabel();
        txtId_c = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        txtMassa = new javax.swing.JTextField();
        txtEstadoConservacao = new javax.swing.JTextField();
        txtPrecoBase = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        labelSubcategoria = new javax.swing.JLabel();
        labelEstadoConservacao = new javax.swing.JLabel();
        labelPrecoBase = new javax.swing.JLabel();
        labelCor = new javax.swing.JLabel();
        labelMassa = new javax.swing.JLabel();
        labelComposicao = new javax.swing.JLabel();
        labelDefeitos = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        selectComposicao = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        selectTipoDePeca = new javax.swing.JComboBox<>();
        selectComposicao1 = new javax.swing.JComboBox<>();
        selectComposicao2 = new javax.swing.JComboBox<>();
        spinnerComposicao = new javax.swing.JSpinner();
        spinnerComposicao1 = new javax.swing.JSpinner();
        spinnerComposicao2 = new javax.swing.JSpinner();
        scrollDefeitos = new javax.swing.JScrollPane();
        painelScrollDefeitos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGerarId = new javax.swing.JButton();
        txtSubcategoria = new javax.swing.JTextField();
        txtTamanho = new javax.swing.JTextField();
        labelComposicao1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Novo Anúncio");
        setPreferredSize(new java.awt.Dimension(1000, 677));
        setVisible(false);

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelId_c.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelId_c.setText("ID_C");
        labelId_c.setToolTipText("");

        labelTipoPeca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTipoPeca.setText("Tipo de Peça");

        txtId_c.setToolTipText("Digite o ID_C (Caso não possua deixe em branco)");
        txtId_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_cActionPerformed(evt);
            }
        });

        btnEnviar.setText("Salvar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Novo anúncio");

        txtMassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMassaActionPerformed(evt);
            }
        });

        txtEstadoConservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoConservacaoActionPerformed(evt);
            }
        });

        txtPrecoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoBaseActionPerformed(evt);
            }
        });

        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        labelSubcategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubcategoria.setText("Subcategoria");

        labelEstadoConservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEstadoConservacao.setText("Estado de conservação");
        labelEstadoConservacao.setToolTipText("");

        labelPrecoBase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPrecoBase.setText("Preço-base (R$)");

        labelCor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCor.setText("Cor Predominante");

        labelMassa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMassa.setText("Massa Estimada (kg)");

        labelComposicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelComposicao.setText("Composição Principal");

        labelDefeitos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDefeitos.setText("Defeitos");

        labelTamanho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTamanho.setText("Tamanho");

        selectComposicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectComposicao.setLightWeightPopupEnabled(false);

        btnCancelar.setText("Cancelar");

        selectTipoDePeca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectTipoDePeca.setLightWeightPopupEnabled(false);
        selectTipoDePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoDePecaActionPerformed(evt);
            }
        });

        selectComposicao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectComposicao1.setLightWeightPopupEnabled(false);

        selectComposicao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectComposicao2.setLightWeightPopupEnabled(false);
        selectComposicao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComposicao2ActionPerformed(evt);
            }
        });

        spinnerComposicao.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        spinnerComposicao1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        spinnerComposicao2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout painelScrollDefeitosLayout = new javax.swing.GroupLayout(painelScrollDefeitos);
        painelScrollDefeitos.setLayout(painelScrollDefeitosLayout);
        painelScrollDefeitosLayout.setHorizontalGroup(
            painelScrollDefeitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        painelScrollDefeitosLayout.setVerticalGroup(
            painelScrollDefeitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        scrollDefeitos.setViewportView(painelScrollDefeitos);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnGerarId.setText("Gerar ID_C");
        btnGerarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarIdActionPerformed(evt);
            }
        });

        txtSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubcategoriaActionPerformed(evt);
            }
        });

        txtTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanhoActionPerformed(evt);
            }
        });

        labelComposicao1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelComposicao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelComposicao1.setText("%");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelId_c)
                    .addComponent(labelCor)
                    .addComponent(labelSubcategoria)
                    .addComponent(labelTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCor)
                    .addComponent(labelMassa)
                    .addComponent(txtMassa)
                    .addComponent(labelEstadoConservacao)
                    .addComponent(txtEstadoConservacao)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(txtId_c, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerarId))
                    .addComponent(txtSubcategoria)
                    .addComponent(txtTamanho)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTipoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDefeitos)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecoBase)
                    .addComponent(txtPrecoBase)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectComposicao1, javax.swing.GroupLayout.Alignment.LEADING, 0, 236, Short.MAX_VALUE)
                            .addComponent(selectComposicao2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectComposicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerComposicao1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(spinnerComposicao, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(spinnerComposicao2)))
                    .addComponent(scrollDefeitos, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(selectTipoDePeca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(labelComposicao)
                        .addGap(108, 108, 108)
                        .addComponent(labelComposicao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelTitulo)
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGerarId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtId_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selectTipoDePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollDefeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(labelComposicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectComposicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerComposicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectComposicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerComposicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(txtPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(labelMassa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMassa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEstadoConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        txtId_c.getAccessibleContext().setAccessibleName("Digite o ID_C (Caso não possua deixe em branco)");

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);
        panel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectComposicao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComposicao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectComposicao2ActionPerformed

    private void selectTipoDePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoDePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoDePecaActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtPrecoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoBaseActionPerformed

    private void txtEstadoConservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoConservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoConservacaoActionPerformed

    private void txtMassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMassaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMassaActionPerformed

    private void txtId_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_cActionPerformed

    private void btnGerarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarIdActionPerformed

    private void txtSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubcategoriaActionPerformed

    private void txtTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanhoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGerarId;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelComposicao;
    private javax.swing.JLabel labelComposicao1;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelDefeitos;
    private javax.swing.JLabel labelEstadoConservacao;
    private javax.swing.JLabel labelId_c;
    private javax.swing.JLabel labelMassa;
    private javax.swing.JLabel labelPrecoBase;
    private javax.swing.JLabel labelSubcategoria;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelTipoPeca;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelScrollDefeitos;
    private java.awt.Panel panel1;
    private javax.swing.JScrollPane scrollDefeitos;
    private javax.swing.JComboBox<String> selectComposicao;
    private javax.swing.JComboBox<String> selectComposicao1;
    private javax.swing.JComboBox<String> selectComposicao2;
    private javax.swing.JComboBox<String> selectTipoDePeca;
    private javax.swing.JSpinner spinnerComposicao;
    private javax.swing.JSpinner spinnerComposicao1;
    private javax.swing.JSpinner spinnerComposicao2;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtEstadoConservacao;
    private javax.swing.JTextField txtId_c;
    private javax.swing.JTextField txtMassa;
    private javax.swing.JTextField txtPrecoBase;
    private javax.swing.JTextField txtSubcategoria;
    private javax.swing.JTextField txtTamanho;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComboBox<String> getSelectComposicao() {
        return selectComposicao;
    }

    @Override
    public JPanel getPainelScrollDefeitos() {
        return painelScrollDefeitos;
    }

    @Override
    public JScrollPane getScrollDefeitos() {
        return scrollDefeitos;
    }

    @Override
    public JComboBox<String> getSelectComposicao1() {
        return selectComposicao1;
    }

    @Override
    public JComboBox<String> getSelectComposicao2() {
        return selectComposicao2;
    }

    @Override
    public JSpinner getSpinnerComposicao() {
        return spinnerComposicao;
    }

    @Override
    public JSpinner getSpinnerComposicao1() {
        return spinnerComposicao1;
    }

    @Override
    public JSpinner getSpinnerComposicao2() {
        return spinnerComposicao2;
    }
    
    @Override
    public JTextField getTxtSubcategoria() {
        return txtSubcategoria;
    }
    
    @Override
    public JTextField getTxtCor() {
        return txtCor;
    }
    
    @Override
    public JTextField getTxtEstadoConservacao() {
        return txtEstadoConservacao;
    }

    @Override
    public JTextField getTxtId_c() {
        return txtId_c;
    }

    @Override
    public JTextField getTxtMassa() {
        return txtMassa;
    }

    @Override
    public JTextField getTxtTamanho() {
        return txtTamanho;
    }

    @Override
    public JComboBox<String> getSelectTipoDePeca() {
        return selectTipoDePeca;
    }

    @Override
    public JTextField getTxtPrecoBase() {
        return txtPrecoBase;
    }
    
    @Override
    public JButton getBtnEnviar() {
        return btnEnviar;
    }
    
    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }
    
    @Override
    public JButton getBtnGerarId() {
        return btnGerarId;
    }

    @Override
    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JLabel getLabelId_c() {
        return labelId_c;
    }

    public JLabel getLabelPrecoBase() {
        return labelPrecoBase;
    }
    
    
    
    
    
    

}


