/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.brechosustentavel.view;

import javax.swing.JButton;

/**
 *
 * @author kaila
 */
public class JanelaEscolhaPerfilView extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaEscolhaPerfilView
     */
    public JanelaEscolhaPerfilView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComprador = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        lblEscolhaPerfil = new javax.swing.JLabel();

        setTitle("Escolha de Perfil");

        btnComprador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComprador.setText("Comprador");

        btnVendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVendedor.setText("Vendedor");

        lblEscolhaPerfil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEscolhaPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscolhaPerfil.setText("Em que perfil você deseja entrar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnComprador, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblEscolhaPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lblEscolhaPerfil)
                .addGap(64, 64, 64)
                .addComponent(btnComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprador;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JLabel lblEscolhaPerfil;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnComprador() {
        return btnComprador;
    }

    public JButton getBtnVendedor() {
        return btnVendedor;
    }

    
}
