/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.brechosustentavel.view;

import java.beans.PropertyVetoException;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTable;

/**
 *
 * @author thiag
 */
public class JanelaPrincipalView extends javax.swing.JInternalFrame implements IJanelaPrincipalView{

    /**
     * Creates new form JanelaPrincipal
     * @throws java.beans.PropertyVetoException
     */
    public JanelaPrincipalView() throws PropertyVetoException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        buttonVisualizar = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonManterTipo = new javax.swing.JButton();
        buttonManterComposicao = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuVisualizarPerfil = new javax.swing.JMenu();
        menuPerfil = new javax.swing.JMenu();
        opcTrocarPerfil = new javax.swing.JMenuItem();
        opcAddPerfil = new javax.swing.JMenuItem();
        menuConfiguracao = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bem-vindo Vendedor!");
        setPreferredSize(new java.awt.Dimension(1000, 677));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        buttonVisualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonVisualizar.setText("Visualizar");
        buttonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarActionPerformed(evt);
            }
        });

        buttonAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAdicionar.setText("Adicionar Anúncio");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonManterTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonManterTipo.setText("Gerenciar tipos de peças");
        buttonManterTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManterTipoActionPerformed(evt);
            }
        });

        buttonManterComposicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonManterComposicao.setText("Gerenciar Composicoes");
        buttonManterComposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManterComposicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(buttonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonManterTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonManterComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonManterTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonManterComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        menuVisualizarPerfil.setText("Visualizar Perfil");
        menuBar.add(menuVisualizarPerfil);

        menuPerfil.setText("Perfil");
        menuPerfil.setToolTipText("");

        opcTrocarPerfil.setText("Trocar perfil");
        menuPerfil.add(opcTrocarPerfil);

        opcAddPerfil.setText("Adicionar novo perfil");
        menuPerfil.add(opcAddPerfil);

        menuBar.add(menuPerfil);

        menuConfiguracao.setText("Configuração");
        menuBar.add(menuConfiguracao);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVisualizarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonManterTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManterTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonManterTipoActionPerformed

    private void buttonManterComposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManterComposicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonManterComposicaoActionPerformed

    @Override
    public JButton getButtonAdicionar() {
        return buttonAdicionar;
    }

    @Override
    public JButton getButtonVisualizar() {
        return buttonVisualizar;
    }

    @Override
    public JTable getjTable1() {
        return jTable1;
    }

    public JMenu getMenuConfiguracao() {
        return menuConfiguracao;
    }

    public JMenu getMenuPerfil() {
        return menuPerfil;
    }

    public JMenu getMenuVisualizarPerfil() {
        return menuVisualizarPerfil;
    }

    public JMenuItem getOpcAddPerfil() {
        return opcAddPerfil;
    }

    public JMenuItem getOpcTrocarPerfil() {
        return opcTrocarPerfil;
    }

    public JButton getButtonManterTipo() {
        return buttonManterTipo;
    }

    public JButton getButtonManterComposicao() {
        return buttonManterComposicao;
    }
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonManterComposicao;
    private javax.swing.JButton buttonManterTipo;
    private javax.swing.JButton buttonVisualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConfiguracao;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuVisualizarPerfil;
    private javax.swing.JMenuItem opcAddPerfil;
    private javax.swing.JMenuItem opcTrocarPerfil;
    // End of variables declaration//GEN-END:variables
}
